# GAME SETUP
GAME_TITLE_WINDOW = "Spider"
START_WIDTH, START_HEIGHT = 800, 600
FPS = 60
# ----------

# MAIN MENU
MENU_WIDTH, MENU_HEIGHT = 400, 300
MENU_X = (MENU_WIDTH*2 - MENU_WIDTH) // 2
MENU_Y = (MENU_HEIGHT*2 - MENU_HEIGHT) // 2

SETTINGS_OPTIONS_START = ["Start","Fullscreen","Volume","Exit game"]
SETTINGS_OPTIONS_GAME = ["Return to game","Fullscreen","Volume","Exit game"]
# ----------

# GAME TILES
TILE_W, TILE_H = 32, 16 
TILE_COUNT_W, TILE_COUNT_H = 12, 18
# ----------

# EGG
SHORT_EGG_TIMER = 40000
MEDIUM_EGG_TIMER = 60000
LONG_EGG_TIMER = 100000

MAX_EGGS = 10
# ----------