GAME_TITLE_WINDOW = "Spider"
FPS = 60

WIDTH, HEIGHT = 800, 600  # Window size
HALF_WIDTH, HALF_HEIGHT = (WIDTH/2), (HEIGHT/2)+50 # Map center
TILE_W, TILE_H = 32, 16 
TILE_COUNT_W, TILE_COUNT_H = 12, 18